# Generated by Django 4.1.7 on 2023-03-08 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_date', models.DateField()),
                ('number', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_card.holder')),
            ],
        ),
    ]
