# Generated by Django 4.1.7 on 2023-03-09 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card', '0002_alter_holder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='brand',
            field=models.CharField(default='Test Brand', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cvv',
            field=models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
