# Generated by Django 4.1.7 on 2023-03-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card', '0004_alter_creditcard_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.CharField(max_length=255),
        ),
    ]
